# Generated by Django 5.0 on 2023-12-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_profile_facebooks_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebooks_url',
            new_name='facebook_url',
        ),
    ]
